include:
  - board: eyelash_corne_right
    shield: eyelash_corne_right nice_oled
    
  - board: eyelash_corne_left
    shield: eyelash_corne_left nice_oled
    
  - board: nice_nano_v2
    shield: settings_reset
