include:
  - board: eyelash_nano
    shield: eyelash_corne_right nice_oled
  - board: eyelash_nano
    shield: eyelash_corne_left nice_oled
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano_v2
    shield: settings_reset